modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="kimetsuaddon"
version="1.0.0"
displayName="Kimetsu Addon"
description="Addon para o mod Kimetsu no Yaiba"
authors="Seu Nome"

[[dependencies.kimetsuaddon]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kimetsuaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.kimetsuaddon]]
    modId="kimetsunoyaiba"
    mandatory=true
    versionRange="[38.2]"
    ordering="AFTER"
    side="BOTH"
